name: Dispatch

on:   
  push:
    branches: master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger another workflow
      env:
        API_URL: https://api.github.com/repos/Beanie95/Course-Java-OOP/actions/workflows/Trigger_Workflow.yml/dispatches
        API_TOKEN: ${{ secrets.GITHUBTOKEN }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $GITHUBTOKEN" \
          -H "Content-Type: application/json" \
          -d '{"ref":"main","inputs":{"environment":"qa"}}' \
          $API_URL
