name: Trigger_Workflow

on:
  [workflow_dispatch]

jobs:
  run-cmd-script:
    runs-on: [self-hosted, windows]
    if: contains(github.event.head_commit.message, '[run-ci]')

    steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    - name: Print inputs
      run: |
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Version: ${{ github.event.inputs.version }}"
